### ISSUE TITLE
AvaliacaoA4.2

### ISSUE THREAD

**Issue by le-adrielli** [waessman/Projeto-MC426#25]
-  Dispensable: 
> As funções de cadastro de usuários e de empresas fazem a mesma coisa, mas com códigos diferentes. Além disso existem alguns testes sendo feitos pelo backend e pelo frontend;

- Change Preventers:
>  - Dados sobre o banco de dados em alguns lugares estão sendo usados a partir de variáveis mapeadas no file .env, o que facilita a modificação e tornam o código menos rígido, mas em alguns lugares estão sendo escrito os valores diretamente, o que pode causar problemas caso ocorra uma mudança no futuro;
>  - Padronizar valores de retorno e mensagens;

- Couplers : 
> No cadastro de empresas o controller que chama a função para cadastrar uma nova empresa está muito dependente de detalhes de implementação internos, esperando valores específicos que sozinhos não representam muita coisa;

-  Bloaters:
> Muitos arquivos diferentes que dificultam a leitura do código. Após resolver o primeiro dispensable seria interessante colocar as funções relacionados a cadastros, tanto de usuários quando empresas, nos mesmos arquivos, mantendo uma boa descrição de cada uma.

**Comment by MarinaldoSA** [comment]
Nova Explicação da Atividade 4.2

**Categoria: Dispensable
-Duplicated Code**
Esse code smell ocorre quando dois fragmentos de código são praticamente idênticos. Isso acontece com as funções de cadastro de usuários e de empresas que fazem a mesma coisa, mas com códigos diferentes. Para refatorar, foi criada uma única função insereNovoUsuario substituindo e preservando a funcionalidade das duas funções removidas.

**Categoria: Change Prevente
-Shotgun Surgery**
Esse code smell ocorre quando ao fazer uma única mudança simples no código somos obrigados a alterar em múltiplas partes do código. Isso ocorre com a validação de email e verificação de email duplicado, pois em caso de alterar o algoritmo usado para fazer essas validações teríamos que alterar em diferentes pontos do código. Para refatorar, extraímos a função validaEmail e verificaEmailDuplicado, que são função de uso recorrente, para uma nova classe validations assim quando for reutilizar, podemos reaproveitar o algoritmo já criado.

**Categoria: Couple
-Inappropriate Intimacy**
Esse code smell ocorre quando um método utiliza detalhes da implementação de outros métodos. Isso ocorre nas função empresaCadastro/usuárioCadastro onde era tratado o retorno (a variável result) da função insereNovoUsuario (merge da função insereNovaEmpresa/ insereNovoUsuario) sendo necessario saber detalhes da implementação dos models dentro da controller para assim modificar seu retorno. Para refatorar, esse fragmento de código foi extraído para dentro da função insereNovoUsuario onde é tratado o resultado em caso de sucesso ou erro, dessa forma a controller apenas repassa o json result sem ter que saber detalhes do objeto que foi manipulado em outra função.

**Comment by waessman** [comment]
Adicionada tratativa na PR #35 de um code smell de categoria Change Preventer, do tipo Shotgun Surgery.
Ao ser necessário alterar alguma mensagem de retorno da API, era necessário buscá-la em diversos lugares diferentes, visto que a mesma mensagem era retornada de maneira fixa em vários arquivos, desta maneira ficaram todas centralizadas e para fazer qualquer alteração só se muda apenas um arquivo.

**Comment by Gustavosbl** [comment]
Feita a refatoração do code smell de categoria Change Preventer (Shotgun Surgery) a respeito das validações de e-mail teve sua implementação realizada no commit
https://github.com/waessman/Projeto-MC426/commit/1d48732bb49d12a71bd6be2a18e40b610142fe84

**Comment by nullJonas** [comment]
Identifiquei um code smell da categoria Long Parameter List na função criar em model_processos.js 
[Nesse commit](https://github.com/waessman/Projeto-MC426/commit/66caadb9f38f60ce8007d56b09d3d1a8179d13a4) o código foi refatorado para corrigí-lo, aplicando a técnica Preserve Whole Object.

O mesmo commit também corrigiu um bug que fazia com que o link externo fornecido pelas empresas na criação dos processos não fosse salvo.
