### ISSUE TITLE
Avaliação A5

### ISSUE THREAD

**Issue by nullJonas** [waessman/Projeto-MC426#28]
Os casos de teste foram construídos examinando partes do código e construindo grafos de causa e efeito para encontrar os possíveis caminhos de execução. Cada caminho diferente foi então considerado como uma classe de equivalência diferente, e foram criados testes que cobrem todas as classes de equivalência encontradas.

Evidência dos testes passando:
![image](https://github.com/waessman/Projeto-MC426/assets/83377242/53250939-aed8-4ac4-917e-bdf715751ed6)

**Comment by nullJonas** [comment]
fechei sem querer a issue

**Comment by le-adrielli** [comment]
Testes de Cadastro de usuário, empresas e de Login implementados inicialmente nesse [commit](https://github.com/waessman/Projeto-MC426/commit/76450f4c8262aa2f971c32c076d27a448686d8c7#diff-a7636fee1d704daa394a114d78a11bbfceb4922a071366f77f83ed92232b8771)

nos arquivos na pasta test
