### ISSUE TITLE
Avaliação 4.1

### ISSUE THREAD

**Issue by le-adrielli** [waessman/Projeto-MC426#34]

**Comment by MarinaldoSA** [comment]
[Commit ](https://github.com/waessman/Projeto-MC426/commit/2cc020a3d001946bf50985e0b46aced8e0316112)de criação do dagrama + descricao

**Comment by nullJonas** [comment]
[Commit](https://github.com/waessman/Projeto-MC426/commit/f2daffb645eab6e35d2b95e8e0fc9ecc42a82a97) de edição da descrição dos componentes no novo diagrama atualizado.

**Comment by waessman** [comment]
[Commit](https://github.com/waessman/Projeto-MC426/commit/02a0de423b3c69435f98cd523316f2912e8162a9) de edição, exemplificando melhor a implementação do padrão MVC adotado em nosso projeto
